version: '3.8'

services:
  db:
    image: postgis/postgis:14-3.3
    environment:
      - POSTGRES_USER=furher
      - POSTGRES_PASSWORD=123gr
      - POSTGRES_DB=analysis_db
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq

  dramatiq_worker:
    build: .
    command: dramatiq Worker/ndvi_dramatiq/task.py --processes 1 --threads 4 --broker "rabbitmq://user:password@rabbitmq:5672//"
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - db